version: "3.8"

services:

  mysqlsrv:
    image: mysql
    container_name: mysql-server
    restart: unless-stopped
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      MYSQL_USER: fiap
      MYSQL_PASSWORD: fiap123
      MYSQL_ROOT_PASSWORD: fiap123
    ports:
      - "3306:3306"
    networks:
      - fiap-compose-network

  redis:
    image: redis
    container_name: redis-server
    restart: unless-stopped
    command: redis-server --requirepass fiap123
    ports:
      - "6379:6379"
    networks:
      - fiap-compose-network

  mongo:
    image: mongo
    container_name: mongo-db
    ports:
      - "27017:27017"
    networks:
      - fiap-compose-network

  neo4j:
    image: neo4j:3.5
    restart: unless-stopped
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - ./conf:/conf
      - ./data:/data
      - ./import:/import
      - ./logs:/logs
      - ./plugins:/plugins
    environment:
      - NEO4J_dbms_memory_pagecache_size=512M
      - NEO4J_dbms.memory.heap.initial_size=512M
      - NEO4J_dbms_memory_heap_max__size=1G

networks:
  fiap-compose-network: