CREATE DATABASE IF NOT EXISTS vendasjpa;
CREATE DATABASE IF NOT EXISTS conceitos;
CREATE DATABASE IF NOT EXISTS dbtarefas;
CREATE DATABASE IF NOT EXISTS dbprodutos;
CREATE DATABASE IF NOT EXISTS redis;

GRANT ALL PRIVILEGES ON *.* TO 'fiap'@'%';